import { notFound, redirect } from "next/navigation";
import Link from "next/link";
import Image from "next/image";
import { SiteShell } from "@/components/site-shell";
import {AccountTypeBadges} from "@/components/account-type-badges";
import {PrimaryProduct,ProductIcon} from "@/components/product-brand";
import { publicDbRpc } from "@/lib/server";
import { money, normalizeHandle, validHandle, type SellerLossStats, type PublicLoss } from "@/lib/domain";
export const dynamic="force-dynamic";
export default async function SellerPage({params}:{params:Promise<{handle:string}>}){
  const handle=normalizeHandle((await params).handle);if(!validHandle(handle))notFound();
  let result:{seller?:SellerLossStats;reports?:PublicLoss[];redirect?:string}|null;
  try{result=await publicDbRpc("get_public_seller",{p_handle:handle})}
  catch{return <SellerUnavailable/>}
  if(result?.redirect)redirect(`/seller/${result.redirect}`);if(!result?.seller)notFound();const stats=result.seller,rows=result.reports||[];
  const count=(value:number|null|undefined)=>new Intl.NumberFormat("en-PH").format(value||0);
  const issueLabel:Record<PublicLoss["loss_issue"],string>={not_delivered:"Not delivered",refund_not_received:"Refund not received",other_unresolved:"Other unresolved issue"};
  return <SiteShell><main className="mx-auto max-w-[1380px] px-5 pb-20 pt-10 md:px-9 md:pt-16"><Link href="/#gallery" className="gallery-label text-muted-foreground hover:text-foreground">← Back to index</Link><section className="gallery-card noise relative mt-8 min-h-[420px] border border-foreground bg-foreground p-6 text-background md:min-h-[540px] md:p-10"><div className="relative flex justify-between gap-3 gallery-label"><span>Hall record / Seller profile</span><span className="text-right">Reviewed buyer claims</span></div><div className="relative mt-16 min-w-0 md:mt-24">{stats.has_avatar&&<Image unoptimized src={`/api/sellers/${stats.id}/avatar?v=${encodeURIComponent(stats.avatar_updated_at||"")}`} alt={`Moderator-selected reference image for @${stats.username}`} width={160} height={160} className="mb-8 size-28 border border-background/30 object-cover md:size-40"/>}<PrimaryProduct product={stats.primary_account_type} inverse/><AccountTypeBadges types={stats.account_types||[]}/><h1 className="mt-6 break-all text-[clamp(2.5rem,10vw,10rem)] font-semibold leading-[.82] tracking-[-.09em] sm:text-[clamp(3.7rem,10vw,10rem)]">@{stats.username}</h1><div className="mt-10 grid grid-cols-2 border-l border-t border-background/30 md:grid-cols-4"><ProfileMetric label="Reported purchase value" value={money(stats.reported_purchase_value)}/><ProfileMetric label="Accounts reported purchased" value={count(stats.accounts_reported_purchased)}/><ProfileMetric label="Amount still unresolved" value={money(stats.unresolved_amount)}/><ProfileMetric label="Approved open reports" value={count(stats.report_count)}/></div>{stats.account_type_breakdown?.length>0&&<div className="mt-8 flex flex-wrap gap-2">{stats.account_type_breakdown.map(type=><span key={`${type.slug}-${type.label}`} className="inline-flex items-center gap-2 border border-background/30 px-3 py-2 text-xs"><ProductIcon slug={type.slug} label={type.label}/>{type.label} · {count(type.accounts)}</span>)}</div>}</div></section>
    <section className="mt-16"><div className="flex items-end justify-between gap-4 border-b-2 border-foreground pb-4"><div><p className="gallery-label text-muted-foreground">Public record</p><h2 className="mt-2 text-4xl font-semibold tracking-[-.07em] md:text-6xl">Open reports.</h2></div><span className="gallery-label text-muted-foreground">{rows.length} shown</span></div><div>{rows.map((row,index)=><article key={row.id} className="grid gap-4 border-b border-foreground/20 py-5 md:grid-cols-[55px_minmax(0,1fr)_170px_100px] md:items-start md:gap-5"><span className="gallery-label text-muted-foreground">{String(index+1).padStart(2,"0")}</span><div><p className="text-lg font-semibold">{issueLabel[row.loss_issue]}</p>{row.items?.length?<div className="mt-3 space-y-2">{row.items.map(item=><div key={item.id} className="grid grid-cols-[28px_minmax(0,1fr)_auto] items-center gap-2 text-xs"><ProductIcon slug={item.account_type_slug} label={item.label} size={22}/><span>{item.label} · {item.quantity} × {money(item.unit_price)}</span><span className="font-mono tabular">{money(item.total_amount)}</span></div>)}</div>:<div className="mt-2"><AccountTypeBadges types={row.account_types||[]}/><p className="mt-2 text-xs text-muted-foreground">{row.quantity} × {money(row.unit_price)} paid</p></div>}</div><div><span className="gallery-label text-muted-foreground">Still unresolved</span><strong className="mt-1 block font-mono text-lg font-medium tabular">{money(row.unresolved_amount)}</strong></div><Link href={`/correct/${row.id}`} className="min-h-10 content-center text-xs font-semibold underline underline-offset-4">Correct</Link></article>)}</div><p className="mt-7 max-w-xl text-xs leading-5 text-muted-foreground">Buyer reports are reviewed for inclusion, not independently verified. Product marks identify reported products and do not imply affiliation or endorsement. Seller images are moderator-selected references and do not prove identity or wrongdoing. <Link href="/methodology" className="font-semibold text-foreground underline underline-offset-4">How rankings work</Link></p></section></main></SiteShell>;
}
function ProfileMetric({label,value}:{label:string;value:string}){return <div className="min-w-0 border-b border-r border-background/30 p-3 md:p-5"><p className="gallery-label text-background/55">{label}</p><p className="mt-2 break-all font-mono text-lg font-semibold tabular md:text-2xl">{value}</p></div>}
function SellerUnavailable(){return <SiteShell><main className="mx-auto grid min-h-[65dvh] max-w-[1380px] place-items-center px-5 text-center md:px-9"><div><p className="gallery-label text-muted-foreground">Seller index</p><h1 className="mt-4 text-5xl font-semibold tracking-[-.07em]">Records unavailable.</h1><p className="mt-4 text-sm text-muted-foreground">The data service is not connected right now.</p><Link href="/" className="mt-8 inline-block border-b border-foreground pb-1 text-xs font-semibold uppercase tracking-wide">Back to index</Link></div></main></SiteShell>}
