import { notFound, redirect } from "next/navigation";
import Link from "next/link";
import { SiteShell } from "@/components/site-shell";
import { dbGet } from "@/lib/server";
import { money, normalizeHandle, validHandle, type SellerLossStats, type PublicLoss } from "@/lib/domain";
export const dynamic="force-dynamic";
export default async function SellerPage({params}:{params:Promise<{handle:string}>}){
  const handle=normalizeHandle((await params).handle);if(!validHandle(handle))notFound();
  let stats:SellerLossStats[];
  try{stats=await dbGet<SellerLossStats[]>("seller_loss_statistics",`select=*&normalized_username=eq.${encodeURIComponent(handle)}&limit=1`)}
  catch{return <SellerUnavailable/>}
  if(!stats[0]) {const old=await dbGet<{merged_into:string|null}[]>("sellers",`select=merged_into&normalized_username=eq.${encodeURIComponent(handle)}&status=eq.merged&limit=1`);if(old[0]?.merged_into){const target=await dbGet<{normalized_username:string}[]>("sellers",`select=normalized_username&id=eq.${old[0].merged_into}&limit=1`);if(target[0])redirect(`/seller/${target[0].normalized_username}`);}notFound();}
  let rows:PublicLoss[];
  try{rows=await dbGet<PublicLoss[]>("public_loss_rows",`select=*&seller_id=eq.${stats[0].id}&order=purchase_date.desc,created_at.desc,id.desc&limit=100`)}
  catch{return <SellerUnavailable/>}
  const issueLabel:Record<PublicLoss["loss_issue"],string>={not_delivered:"Not delivered",refund_not_received:"Refund not received",other_unresolved:"Other unresolved issue"};
  return <SiteShell><main className="mx-auto max-w-[1380px] px-5 pb-20 pt-10 md:px-9 md:pt-16"><Link href="/#gallery" className="gallery-label text-muted-foreground hover:text-foreground">← Back to index</Link><section className="gallery-card noise relative mt-8 min-h-[420px] border border-foreground bg-foreground p-6 text-background md:min-h-[540px] md:p-10"><div className="relative flex justify-between gallery-label"><span>Seller profile</span><span>{stats[0].report_count} open {stats[0].report_count===1?"report":"reports"}</span></div><div className="relative mt-32 md:mt-52"><h1 className="break-all text-[clamp(3.7rem,10vw,10rem)] font-semibold leading-[.82] tracking-[-.09em]">@{stats[0].username}</h1><div className="mt-10 flex flex-wrap items-end justify-between gap-5 border-t border-background/30 pt-5"><div><p className="gallery-label text-background/55">Reported unresolved amount</p><p className="mt-3 font-mono text-4xl tabular md:text-6xl">{money(stats[0].unresolved_amount)}</p></div><span className="gallery-label">PHP / Current</span></div></div></section>
    <section className="mt-16"><div className="flex items-end justify-between gap-4 border-b-2 border-foreground pb-4"><div><p className="gallery-label text-muted-foreground">Public record</p><h2 className="mt-2 text-4xl font-semibold tracking-[-.07em] md:text-6xl">Open reports.</h2></div><span className="gallery-label text-muted-foreground">{rows.length} shown</span></div><div>{rows.map((row,index)=><article key={row.id} className="grid gap-3 border-b border-foreground/20 py-5 md:grid-cols-[55px_1fr_1fr_170px_100px] md:items-center md:gap-5"><span className="gallery-label text-muted-foreground">{String(index+1).padStart(2,"0")}</span><div><p className="text-lg font-semibold">{issueLabel[row.loss_issue]}</p><p className="mt-1 text-xs text-muted-foreground">Purchased {row.purchase_date}</p></div><p className="text-xs text-muted-foreground">{row.quantity} × {money(row.unit_price)} paid</p><strong className="font-mono text-lg font-medium tabular">{money(row.unresolved_amount)}</strong><Link href={`/correct/${row.id}`} className="min-h-10 content-center text-xs font-semibold underline underline-offset-4">Correct</Link></article>)}</div><p className="mt-7 max-w-xl text-xs leading-5 text-muted-foreground">Buyer reports are reviewed for inclusion, not independently verified. <Link href="/methodology" className="font-semibold text-foreground underline underline-offset-4">How rankings work</Link></p></section></main></SiteShell>;
}
function SellerUnavailable(){return <SiteShell><main className="mx-auto grid min-h-[65dvh] max-w-[1380px] place-items-center px-5 text-center md:px-9"><div><p className="gallery-label text-muted-foreground">Seller index</p><h1 className="mt-4 text-5xl font-semibold tracking-[-.07em]">Records unavailable.</h1><p className="mt-4 text-sm text-muted-foreground">The data service is not connected right now.</p><Link href="/" className="mt-8 inline-block border-b border-foreground pb-1 text-xs font-semibold uppercase tracking-wide">Back to index</Link></div></main></SiteShell>}
