import { notFound, redirect } from "next/navigation";
import Link from "next/link";
import { SiteShell } from "@/components/site-shell";
import { publicDbRpc } from "@/lib/server";
import { money, normalizeHandle, validHandle, type SellerLossStats, type PublicLoss } from "@/lib/domain";
export const dynamic="force-dynamic";
export default async function SellerPage({params}:{params:Promise<{handle:string}>}){
  const handle=normalizeHandle((await params).handle);if(!validHandle(handle))notFound();
  let result:{seller?:SellerLossStats;reports?:PublicLoss[];redirect?:string}|null;
  try{result=await publicDbRpc("get_public_seller",{p_handle:handle})}
  catch{return <SellerUnavailable/>}
  if(result?.redirect)redirect(`/seller/${result.redirect}`);if(!result?.seller)notFound();const stats=result.seller,rows=result.reports||[];
  const issueLabel:Record<PublicLoss["loss_issue"],string>={not_delivered:"Not delivered",refund_not_received:"Refund not received",other_unresolved:"Other unresolved issue"};
  return <SiteShell><main className="mx-auto max-w-[1380px] px-5 pb-20 pt-10 md:px-9 md:pt-16"><Link href="/#gallery" className="gallery-label text-muted-foreground hover:text-foreground">← Back to index</Link><section className="gallery-card noise relative mt-8 min-h-[420px] border border-foreground bg-foreground p-6 text-background md:min-h-[540px] md:p-10"><div className="relative flex justify-between gap-3 gallery-label"><span>Seller profile</span><span className="text-right">{stats.report_count} open {stats.report_count===1?"report":"reports"}</span></div><div className="relative mt-32 min-w-0 md:mt-52"><h1 className="break-all text-[clamp(2.5rem,10vw,10rem)] font-semibold leading-[.82] tracking-[-.09em] sm:text-[clamp(3.7rem,10vw,10rem)]">@{stats.username}</h1><div className="mt-10 flex min-w-0 flex-wrap items-end justify-between gap-5 border-t border-background/30 pt-5"><div className="min-w-0"><p className="gallery-label text-background/55">Reported unresolved amount</p><p className="mt-3 break-all font-mono text-[clamp(1.5rem,8vw,2.25rem)] tabular md:text-6xl">{money(stats.unresolved_amount)}</p></div><span className="gallery-label">PHP / Current</span></div></div></section>
    <section className="mt-16"><div className="flex items-end justify-between gap-4 border-b-2 border-foreground pb-4"><div><p className="gallery-label text-muted-foreground">Public record</p><h2 className="mt-2 text-4xl font-semibold tracking-[-.07em] md:text-6xl">Open reports.</h2></div><span className="gallery-label text-muted-foreground">{rows.length} shown</span></div><div>{rows.map((row,index)=><article key={row.id} className="grid gap-3 border-b border-foreground/20 py-5 md:grid-cols-[55px_1fr_1fr_170px_100px] md:items-center md:gap-5"><span className="gallery-label text-muted-foreground">{String(index+1).padStart(2,"0")}</span><div><p className="text-lg font-semibold">{issueLabel[row.loss_issue]}</p><p className="mt-1 text-xs text-muted-foreground">Purchased {row.purchase_date}</p></div><p className="text-xs text-muted-foreground">{row.quantity} × {money(row.unit_price)} paid</p><strong className="font-mono text-lg font-medium tabular">{money(row.unresolved_amount)}</strong><Link href={`/correct/${row.id}`} className="min-h-10 content-center text-xs font-semibold underline underline-offset-4">Correct</Link></article>)}</div><p className="mt-7 max-w-xl text-xs leading-5 text-muted-foreground">Buyer reports are reviewed for inclusion, not independently verified. <Link href="/methodology" className="font-semibold text-foreground underline underline-offset-4">How rankings work</Link></p></section></main></SiteShell>;
}
function SellerUnavailable(){return <SiteShell><main className="mx-auto grid min-h-[65dvh] max-w-[1380px] place-items-center px-5 text-center md:px-9"><div><p className="gallery-label text-muted-foreground">Seller index</p><h1 className="mt-4 text-5xl font-semibold tracking-[-.07em]">Records unavailable.</h1><p className="mt-4 text-sm text-muted-foreground">The data service is not connected right now.</p><Link href="/" className="mt-8 inline-block border-b border-foreground pb-1 text-xs font-semibold uppercase tracking-wide">Back to index</Link></div></main></SiteShell>}
