"use client";
import { useCallback, useEffect, useState } from "react";
import { money } from "@/lib/domain";
type Pending={id:string;seller_id:string;buyer_username:string|null;purchase_date:string;quantity:number;unit_price:string;total_amount:string;loss_issue:string|null;loss_details:string|null;reported_unresolved_amount:string|null;unresolved_amount:string|null;loss_status:string|null;flags:string[];evidence_path:string|null;submitter_fingerprint:string;created_at:string;sellers:{username:string}|null};
type Loss={id:string;buyer_username:string|null;purchase_date:string;loss_issue:string;loss_details:string;reported_unresolved_amount:string;unresolved_amount:string;loss_status:string;created_at:string;sellers:{username:string}|null};
type Correction={id:string;purchase_id:string;issue_type:string;contact_email:string;details:string;created_at:string};
type Seller={id:string;username:string;status:string;created_at:string};
type Audit={id:number;actor:string;action:string;target_type:string;created_at:string};
type Blocked={fingerprint:string;blocked_at:string;blocked_by:string};
type Queue={pending:Pending[];losses:Loss[];corrections:Correction[];sellers:Seller[];audit:Audit[];blocked:Blocked[]};
const date=(v:string)=>new Intl.DateTimeFormat("en-PH",{dateStyle:"medium",timeStyle:"short"}).format(new Date(v));
export function AdminClient({email,signOutHref}:{email:string;signOutHref:string}){
  const [data,setData]=useState<Queue|null>(null),[error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[source,setSource]=useState<string|null>(null),[target,setTarget]=useState<string|null>(null),[amounts,setAmounts]=useState<Record<string,string>>({});
  const load=useCallback(async()=>{try{const r=await fetch("/api/admin",{cache:"no-store"});const j=await r.json() as Queue & {error?:string};if(!r.ok)throw new Error(j.error);setData(j);setError("");}catch(e){setError(e instanceof Error?e.message:"Could not load review queue.");}},[]);
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer);},[load]);
  async function act(action:string,body:Record<string,string>){if(["approve","reject","merge","retract","block","suspend","resolve_loss"].includes(action)&&!window.confirm(`Confirm ${action.replaceAll("_"," ")}?`))return;setBusy(true);setError("");setNotice("");try{const r=await fetch("/api/admin",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,...body})});const j=await r.json() as {error?:string};if(!r.ok)throw new Error(j.error);setNotice("Action saved.");setSource(null);setTarget(null);await load();}catch(e){setError(e instanceof Error?e.message:"Action failed.");}finally{setBusy(false)}}
  const button="min-h-10 rounded-sm border border-foreground/20 bg-card px-3.5 py-2 text-xs font-semibold transition hover:bg-foreground hover:text-background disabled:opacity-50";
  return <main className="mx-auto max-w-[1240px] space-y-14 px-5 py-16 md:px-8 md:py-24"><div className="grid gap-6 border-b border-foreground/12 pb-10 md:grid-cols-[1fr_auto] md:items-end"><div><p className="font-mono text-[10px] uppercase tracking-[.16em] text-muted-foreground">Private workspace</p><h1 className="mt-3 text-5xl font-semibold tracking-[-.07em]">Moderation</h1><p className="mt-3 text-sm text-muted-foreground">Signed in as {email}. Approval publishes a report but does not independently verify it.</p></div><div className="flex items-center gap-3">{data&&<div className="border border-foreground px-4 py-2 font-mono text-xs">{data.pending.length} pending</div>}{signOutHref==="/auth/signout"?<form action={signOutHref} method="post"><button className="inline-flex min-h-10 items-center border border-foreground/20 px-3.5 text-xs font-semibold hover:bg-foreground hover:text-background">Sign out</button></form>:<a href={signOutHref} className="inline-flex min-h-10 items-center border border-foreground/20 px-3.5 text-xs font-semibold hover:bg-foreground hover:text-background">Sign out</a>}</div></div>{error&&<p role="alert" className="border border-foreground bg-card p-3 text-sm" >{error}</p>}{notice&&<p role="status" className="border border-foreground bg-card p-3 text-sm">{notice}</p>}{!data?<p>Loading review queue…</p>:<>
    <section><h2 className="mb-4 text-xl font-semibold">Pending reports <span className="text-muted-foreground">{data.pending.length}</span></h2><div className="space-y-3">{data.pending.length===0?<Empty/>:data.pending.map(p=><article key={p.id} className="border border-border bg-card p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="font-semibold">@{p.sellers?.username||"Unknown seller"} · {p.unresolved_amount?`${money(p.unresolved_amount)} unresolved`:money(p.total_amount)}</p><p className="mt-1 text-xs text-muted-foreground">Buyer: {p.buyer_username || "Not recorded"} · Seller: @{p.sellers?.username || "Unknown seller"}</p><p className="mt-1 text-sm text-muted-foreground">{p.quantity} × {money(p.unit_price)} · purchase {p.purchase_date} · submitted {date(p.created_at)}</p>{p.loss_issue&&<p className="mt-3 text-xs font-semibold uppercase tracking-wide">{p.loss_issue.replaceAll("_"," ")}</p>}{p.loss_details&&<p className="mt-2 max-w-2xl text-sm">{p.loss_details}</p>}{p.flags.length>0&&<p className="mt-2 text-xs font-medium">Flags: {p.flags.join(", ")}</p>}<p className="mt-2 text-xs text-muted-foreground">Record {p.id}</p></div><div className="flex flex-wrap gap-2">{p.evidence_path&&<a href={`/api/admin/evidence/${p.id}`} target="_blank" rel="noreferrer" className={button}>Review evidence</a>}<button disabled={busy} className={button} onClick={()=>act("approve",{id:p.id})}>Approve</button><button disabled={busy} className={button} onClick={()=>act("reject",{id:p.id})}>Reject</button><button disabled={busy} className={button} onClick={()=>act("block",{fingerprint:p.submitter_fingerprint})}>Block submitter</button></div></div></article>)}</div></section>
    <section><h2 className="mb-4 text-xl font-semibold">Approved loss reports <span className="text-muted-foreground">{data.losses.length}</span></h2><div className="space-y-3">{data.losses.length===0?<Empty/>:data.losses.map(p=><article key={p.id} className="border border-border bg-card p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="font-semibold">@{p.sellers?.username||"Unknown seller"} · {money(p.unresolved_amount)} unresolved</p><p className="mt-1 text-xs text-muted-foreground">Buyer: {p.buyer_username || "Not recorded"} · Seller: @{p.sellers?.username || "Unknown seller"}</p><p className="mt-1 text-xs text-muted-foreground">Originally {money(p.reported_unresolved_amount)} · {p.loss_status} · {p.purchase_date}</p><p className="mt-3 text-sm">{p.loss_issue.replaceAll("_"," ")}: {p.loss_details}</p></div><div className="flex flex-wrap items-center gap-2"><label className="sr-only" htmlFor={`amount-${p.id}`}>Adjusted unresolved amount for @{p.sellers?.username}</label><input id={`amount-${p.id}`} inputMode="decimal" value={amounts[p.id]??p.unresolved_amount} onChange={e=>setAmounts(a=>({...a,[p.id]:e.target.value}))} className="h-10 w-28 border border-foreground/20 bg-background px-2 text-sm"/><button disabled={busy} className={button} onClick={()=>act("adjust_loss",{id:p.id,amount:amounts[p.id]??p.unresolved_amount})}>Save amount</button><button disabled={busy||p.loss_status==="resolved"} className={button} onClick={()=>act("resolve_loss",{id:p.id})}>Resolve</button><button disabled={busy} className={button} onClick={()=>act("retract",{id:p.id})}>Retract</button></div></div></article>)}</div></section>
    <section><h2 className="mb-4 text-xl font-semibold">Correction requests <span className="text-muted-foreground">{data.corrections.length}</span></h2><div className="space-y-3">{data.corrections.length===0?<Empty/>:data.corrections.map(c=><article key={c.id} className="rounded-xl border border-border bg-white p-5"><p className="font-semibold">{c.issue_type.replaceAll("_"," ")} · {c.purchase_id}</p><p className="mt-1 text-sm text-muted-foreground">{c.contact_email} · {date(c.created_at)}</p>{c.details&&<p className="mt-2 text-sm">{c.details}</p>}<div className="mt-4 flex flex-wrap gap-2"><button disabled={busy} className={button} onClick={()=>act("retract",{id:c.purchase_id})}>Retract record</button><button disabled={busy} className={button} onClick={()=>act("resolve",{id:c.id})}>Mark resolved</button><button disabled={busy} className={button} onClick={()=>act("dismiss",{id:c.id})}>Dismiss</button></div></article>)}</div></section>
    <section><h2 className="mb-4 text-xl font-semibold">Sellers</h2><p className="mb-3 text-sm text-muted-foreground">Choose a source and active target to merge duplicate handles. The source URL redirects to the target.</p><div className="mb-4 flex flex-wrap items-center gap-3 rounded-lg border border-border bg-white p-4 text-sm"><span>Source: {data.sellers.find(s=>s.id===source)?.username||"None"}</span><span>→</span><span>Target: {data.sellers.find(s=>s.id===target)?.username||"None"}</span><button disabled={busy||!source||!target||source===target} onClick={()=>source&&target&&act("merge",{source,target})} className={button}>Merge sellers</button></div><div className="space-y-2">{data.sellers.map(s=><div key={s.id} className="flex flex-wrap items-center justify-between gap-3 rounded-lg border border-border bg-white p-3 text-sm"><span><strong>@{s.username}</strong> <span className="text-muted-foreground">· {s.status}</span></span><div className="flex flex-wrap gap-2"><button disabled={s.status==="merged"} className={button} onClick={()=>setSource(s.id)}>Use as source</button><button disabled={s.status!=="active"} className={button} onClick={()=>setTarget(s.id)}>Use as target</button>{s.status==="suspended"?<button disabled={busy} className={button} onClick={()=>act("restore",{id:s.id})}>Restore</button>:s.status!=="merged"&&<button disabled={busy} className={button} onClick={()=>act("suspend",{id:s.id})}>Suspend</button>}</div></div>)}</div></section>
    <section><h2 className="mb-4 text-xl font-semibold">Blocked submitters</h2><div className="space-y-2">{data.blocked.map(b=><div key={b.fingerprint} className="flex flex-wrap items-center justify-between gap-3 rounded-lg border border-border bg-white p-3 text-sm"><span className="font-mono text-xs">{b.fingerprint.slice(0,12)}… · {date(b.blocked_at)}</span><button disabled={busy} className={button} onClick={()=>act("unblock",{fingerprint:b.fingerprint})}>Unblock</button></div>)}{!data.blocked.length&&<Empty/>}</div></section>
    <section><h2 className="mb-4 text-xl font-semibold">Audit history</h2><div className="rounded-xl border border-border bg-white">{data.audit.map(a=><div key={a.id} className="flex flex-wrap justify-between gap-2 border-b border-border px-4 py-3 text-sm last:border-0"><span>{a.action.replaceAll("_"," ")} · {a.target_type} · {a.actor}</span><time className="text-muted-foreground">{date(a.created_at)}</time></div>)}{!data.audit.length&&<div className="p-5 text-sm text-muted-foreground">No moderation actions yet.</div>}</div></section>
  </>}</main>;
}
function Empty(){return <div className="rounded-2xl border border-dashed border-foreground/15 bg-card/60 p-7 text-sm text-muted-foreground">Nothing to review.</div>}
