"use client";
import { useCallback, useEffect, useState } from "react";
import { money } from "@/lib/domain";
type Pending={id:string;seller_id:string;purchase_date:string;quantity:number;unit_price:string;total_amount:string;flags:string[];evidence_path:string|null;submitter_fingerprint:string;created_at:string;sellers:{username:string}|null};
type Correction={id:string;purchase_id:string;issue_type:string;contact_email:string;details:string;created_at:string};
type Seller={id:string;username:string;status:string;created_at:string};
type Audit={id:number;actor:string;action:string;target_type:string;created_at:string};
type Blocked={fingerprint:string;blocked_at:string;blocked_by:string};
type Queue={pending:Pending[];corrections:Correction[];sellers:Seller[];audit:Audit[];blocked:Blocked[]};
const date=(v:string)=>new Intl.DateTimeFormat("en-PH",{dateStyle:"medium",timeStyle:"short"}).format(new Date(v));
export function AdminClient({email}:{email:string}){
  const [data,setData]=useState<Queue|null>(null),[error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[source,setSource]=useState<string|null>(null),[target,setTarget]=useState<string|null>(null);
  const load=useCallback(async()=>{try{const r=await fetch("/api/admin",{cache:"no-store"});const j=await r.json() as Queue & {error?:string};if(!r.ok)throw new Error(j.error);setData(j);setError("");}catch(e){setError(e instanceof Error?e.message:"Could not load review queue.");}},[]);
  useEffect(()=>{void load();},[load]);
  async function act(action:string,body:Record<string,string>){if(["approve","reject","merge","retract","block","suspend"].includes(action)&&!window.confirm(`Confirm ${action}?`))return;setBusy(true);setError("");setNotice("");try{const r=await fetch("/api/admin",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,...body})});const j=await r.json() as {error?:string};if(!r.ok)throw new Error(j.error);setNotice("Action saved.");setSource(null);setTarget(null);await load();}catch(e){setError(e instanceof Error?e.message:"Action failed.");}finally{setBusy(false)}}
  const button="rounded-md border border-border bg-white px-3 py-2 text-xs font-medium hover:border-primary hover:text-primary disabled:opacity-50";
  return <main className="mx-auto max-w-[1160px] space-y-11 px-5 py-12 md:px-8"><div><p className="text-xs font-semibold uppercase tracking-[.14em] text-primary">Private workspace</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.05em]">Moderation</h1><p className="mt-2 text-sm text-muted-foreground">Signed in as {email}. Approval makes a report public; it does not independently verify a sale.</p></div>{error&&<p role="alert" className="rounded-md bg-[#fff1f1] p-3 text-sm text-destructive">{error}</p>}{notice&&<p role="status" className="rounded-md bg-accent p-3 text-sm text-primary">{notice}</p>}{!data?<p>Loading review queue…</p>:<>
    <section><h2 className="mb-4 text-xl font-semibold">Pending purchases <span className="text-muted-foreground">{data.pending.length}</span></h2><div className="space-y-3">{data.pending.length===0?<Empty/>:data.pending.map(p=><article key={p.id} className="rounded-xl border border-border bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="font-semibold">@{p.sellers?.username||"Unknown seller"} · {money(p.total_amount)}</p><p className="mt-1 text-sm text-muted-foreground">{p.quantity} × {money(p.unit_price)} · purchase {p.purchase_date} · submitted {date(p.created_at)}</p>{p.flags.length>0&&<p className="mt-2 text-xs font-medium text-destructive">Flags: {p.flags.join(", ")}</p>}<p className="mt-2 text-xs text-muted-foreground">Record {p.id}</p></div><div className="flex flex-wrap gap-2">{p.evidence_path&&<a href={`/api/admin/evidence/${p.id}`} target="_blank" rel="noreferrer" className={button}>Review evidence</a>}<button disabled={busy} className={button} onClick={()=>act("approve",{id:p.id})}>Approve</button><button disabled={busy} className={button} onClick={()=>act("reject",{id:p.id})}>Reject</button><button disabled={busy} className={button} onClick={()=>act("block",{fingerprint:p.submitter_fingerprint})}>Block submitter</button></div></div></article>)}</div></section>
    <section><h2 className="mb-4 text-xl font-semibold">Correction requests <span className="text-muted-foreground">{data.corrections.length}</span></h2><div className="space-y-3">{data.corrections.length===0?<Empty/>:data.corrections.map(c=><article key={c.id} className="rounded-xl border border-border bg-white p-5"><p className="font-semibold">{c.issue_type.replaceAll("_"," ")} · {c.purchase_id}</p><p className="mt-1 text-sm text-muted-foreground">{c.contact_email} · {date(c.created_at)}</p>{c.details&&<p className="mt-2 text-sm">{c.details}</p>}<div className="mt-4 flex flex-wrap gap-2"><button disabled={busy} className={button} onClick={()=>act("retract",{id:c.purchase_id})}>Retract record</button><button disabled={busy} className={button} onClick={()=>act("resolve",{id:c.id})}>Mark resolved</button><button disabled={busy} className={button} onClick={()=>act("dismiss",{id:c.id})}>Dismiss</button></div></article>)}</div></section>
    <section><h2 className="mb-4 text-xl font-semibold">Sellers</h2><p className="mb-3 text-sm text-muted-foreground">Choose a source and active target to merge duplicate handles. The source URL redirects to the target.</p><div className="mb-4 flex flex-wrap items-center gap-3 rounded-lg border border-border bg-white p-4 text-sm"><span>Source: {data.sellers.find(s=>s.id===source)?.username||"None"}</span><span>→</span><span>Target: {data.sellers.find(s=>s.id===target)?.username||"None"}</span><button disabled={busy||!source||!target||source===target} onClick={()=>source&&target&&act("merge",{source,target})} className={button}>Merge sellers</button></div><div className="space-y-2">{data.sellers.map(s=><div key={s.id} className="flex flex-wrap items-center justify-between gap-3 rounded-lg border border-border bg-white p-3 text-sm"><span><strong>@{s.username}</strong> <span className="text-muted-foreground">· {s.status}</span></span><div className="flex flex-wrap gap-2"><button disabled={s.status==="merged"} className={button} onClick={()=>setSource(s.id)}>Use as source</button><button disabled={s.status!=="active"} className={button} onClick={()=>setTarget(s.id)}>Use as target</button>{s.status==="suspended"?<button disabled={busy} className={button} onClick={()=>act("restore",{id:s.id})}>Restore</button>:s.status!=="merged"&&<button disabled={busy} className={button} onClick={()=>act("suspend",{id:s.id})}>Suspend</button>}</div></div>)}</div></section>
    <section><h2 className="mb-4 text-xl font-semibold">Blocked submitters</h2><div className="space-y-2">{data.blocked.map(b=><div key={b.fingerprint} className="flex flex-wrap items-center justify-between gap-3 rounded-lg border border-border bg-white p-3 text-sm"><span className="font-mono text-xs">{b.fingerprint.slice(0,12)}… · {date(b.blocked_at)}</span><button disabled={busy} className={button} onClick={()=>act("unblock",{fingerprint:b.fingerprint})}>Unblock</button></div>)}{!data.blocked.length&&<Empty/>}</div></section>
    <section><h2 className="mb-4 text-xl font-semibold">Audit history</h2><div className="rounded-xl border border-border bg-white">{data.audit.map(a=><div key={a.id} className="flex flex-wrap justify-between gap-2 border-b border-border px-4 py-3 text-sm last:border-0"><span>{a.action.replaceAll("_"," ")} · {a.target_type} · {a.actor}</span><time className="text-muted-foreground">{date(a.created_at)}</time></div>)}{!data.audit.length&&<div className="p-5 text-sm text-muted-foreground">No moderation actions yet.</div>}</div></section>
  </>}</main>;
}
function Empty(){return <div className="rounded-xl border border-border bg-white p-5 text-sm text-muted-foreground">Nothing to review.</div>}
