"use client";
import { useState } from "react";
import Script from "next/script";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
const issues=[ ["wrong_seller","Wrong seller"],["wrong_amount","Wrong quantity or price"],["duplicate","Duplicate record"],["not_a_purchase","Not a purchase"],["other","Something else"] ] as const;
export function CorrectionForm({purchaseId,siteKey}:{purchaseId:string;siteKey:string}) {
  const [issue,setIssue]=useState("wrong_seller"),[email,setEmail]=useState(""),[details,setDetails]=useState(""),[error,setError]=useState(""),[status,setStatus]=useState(""),[saving,setSaving]=useState(false);
  async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setError("");setStatus("");setSaving(true);const form=new FormData(e.currentTarget);try{const res=await fetch("/api/corrections",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({purchaseId,issueType:issue,email,details,turnstileToken:form.get("cf-turnstile-response")||""})});const data=await res.json() as {error?:string};if(!res.ok)throw new Error(data.error||"We couldn't send this request.");setStatus("Correction request received. A moderator will review it.");setDetails("");}catch(err){setError(err instanceof Error?err.message:"We couldn't send this request.");}finally{setSaving(false)}}
  return <form onSubmit={submit} className="mt-8 space-y-6 rounded-xl border border-border bg-white p-6 md:p-8"><fieldset><legend className="mb-3 text-sm font-medium">What needs correcting?</legend><RadioGroup value={issue} onValueChange={setIssue}>{issues.map(([value,label])=><label key={value} className="flex cursor-pointer items-center gap-3 text-sm"><RadioGroupItem value={value} id={value}/>{label}</label>)}</RadioGroup></fieldset><div><label htmlFor="email" className="mb-2 block text-sm font-medium">Your email, for follow-up</label><input id="email" type="email" value={email} onChange={e=>setEmail(e.target.value)} required className="h-12 w-full rounded-md border border-input px-3"/></div><div><label htmlFor="details" className="mb-2 block text-sm font-medium">Brief details <span className="font-normal text-muted-foreground">(optional)</span></label><textarea id="details" maxLength={500} rows={3} value={details} onChange={e=>setDetails(e.target.value)} className="w-full rounded-md border border-input p-3 text-sm"/><p className="mt-1 text-xs text-muted-foreground">Private to moderators. Please do not include sensitive personal information.</p></div>{siteKey&&<><Script src="https://challenges.cloudflare.com/turnstile/v0/api.js" strategy="afterInteractive"/><div className="cf-turnstile" data-sitekey={siteKey}/></>}{error&&<p role="alert" className="text-sm text-destructive">{error}</p>}{status&&<p role="status" className="text-sm text-primary">{status}</p>}<button disabled={saving} className="h-12 rounded-md bg-primary px-6 text-sm font-semibold text-white disabled:opacity-60">{saving?"Sending…":"Send correction request"}</button></form>;
}
