"use client";
import { useRef, useState } from "react";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { TurnstileWidget } from "@/components/turnstile-widget";
const issues=[ ["refund_received","Refund received"],["loss_resolved","Loss resolved"],["wrong_amount","Wrong amount"],["wrong_seller","Wrong seller"],["duplicate","Duplicate report"],["not_a_purchase","Not a purchase"],["other","Something else"] ] as const;
export function CorrectionForm({purchaseId,siteKey}:{purchaseId:string;siteKey:string}) {
  const [issue,setIssue]=useState("refund_received"),[email,setEmail]=useState(""),[details,setDetails]=useState(""),[error,setError]=useState(""),[status,setStatus]=useState(""),[saving,setSaving]=useState(false);
  const errorRef=useRef<HTMLParagraphElement>(null);
  const idempotency=useRef(crypto.randomUUID());
  async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setError("");setStatus("");if(!siteKey){setError("Correction requests are unavailable until human verification is configured.");requestAnimationFrame(()=>errorRef.current?.focus());return}setSaving(true);const form=new FormData(e.currentTarget);try{const res=await fetch("/api/corrections",{method:"POST",headers:{"content-type":"application/json","idempotency-key":idempotency.current},body:JSON.stringify({purchaseId,issueType:issue,email,details,idempotencyKey:idempotency.current,turnstileToken:form.get("cf-turnstile-response")||""})});const data=await res.json() as {error?:string};if(!res.ok)throw new Error(data.error||"We couldn't send this request.");setStatus("Correction request received. A moderator will review it.");setDetails("");idempotency.current=crypto.randomUUID();}catch(err){setError(err instanceof Error?err.message:"We couldn't send this request.");requestAnimationFrame(()=>errorRef.current?.focus())}finally{setSaving(false)}}
  return <form onSubmit={submit} className="retro-window retro-window--cobalt min-w-0 space-y-6 bg-card p-4 sm:p-6 md:p-9"><div className="retro-titlebar -mx-4 -mt-4 mb-5 sm:-mx-6 sm:-mt-6 md:-mx-9 md:-mt-9"><span className="retro-titlebar__dots" aria-hidden="true"><i/><i/><i/></span>REQUEST FORM / PRIVATE</div><div><p className="gallery-label text-muted-foreground">Correction details</p><h2 className="mt-2 text-2xl font-semibold tracking-[-.045em]">What needs correcting?</h2></div><fieldset><legend className="sr-only">Issue type</legend><RadioGroup value={issue} onValueChange={setIssue} className="grid gap-2 sm:grid-cols-2">{issues.map(([value,label])=><label key={value} className="flex min-h-12 cursor-pointer items-center gap-3 border border-foreground/20 bg-background px-4 text-sm transition hover:border-foreground"><RadioGroupItem value={value} id={value}/>{label}</label>)}</RadioGroup></fieldset><div><label htmlFor="email" className="mb-2 block text-xs font-semibold">Your email, for follow-up</label><input id="email" type="email" value={email} onChange={e=>setEmail(e.target.value)} required className="h-12 w-full min-w-0 border border-foreground/25 bg-card px-3"/></div><div><label htmlFor="details" className="mb-2 block text-xs font-semibold">Brief details <span className="font-normal text-muted-foreground">Optional</span></label><textarea id="details" maxLength={500} rows={4} value={details} onChange={e=>setDetails(e.target.value)} className="w-full min-w-0 border border-foreground/25 bg-card p-3 text-sm"/><p className="mt-2 text-xs text-muted-foreground">Do not include passwords, identity documents, addresses, phone numbers, or unrelated third-party information.</p></div>{siteKey&&<TurnstileWidget siteKey={siteKey} action="correction_request"/>}{!siteKey&&<p role="status" className="border border-foreground/25 p-3 text-sm">Correction requests are temporarily unavailable until human verification is configured.</p>}{error&&<p id="correction-error" ref={errorRef} tabIndex={-1} role="alert" className="border-2 border-foreground p-3 text-sm font-medium focus:outline-none">{error}</p>}{status&&<p role="status" className="border border-foreground p-3 text-sm">{status}</p>}<button disabled={saving||!siteKey} className="min-h-12 bg-foreground px-6 text-sm font-semibold text-background disabled:opacity-60">{saving?"Sending…":"Send correction request"}</button></form>;
}
