"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import Link from "next/link";
import Script from "next/script";
import { motion } from "motion/react";
import { ArrowDown, ArrowRight, ArrowUpRight, Check, X } from "lucide-react";
import { SiteShell } from "@/components/site-shell";
import { SellerSearch } from "@/components/seller-search";
import { RecordTrigger } from "@/components/record-trigger";
import { Dialog, DialogContent, DialogDescription, DialogTitle } from "@/components/ui/dialog";
import { manilaToday, money, normalizeHandle, validForumUsername, validHandle, validUnresolvedAmount, type LossOverview, type SellerLossStats } from "@/lib/domain";

const empty:LossOverview={totals:{unresolved_amount:"0.00",report_count:0,visible_sellers:0},leaders:[],recent:[]};

export function HomeClient({siteKey,ready}:{siteKey:string;ready:boolean}){
  const [overview,setOverview]=useState<LossOverview>(empty),[loading,setLoading]=useState(true),[unavailable,setUnavailable]=useState(false),[open,setOpen]=useState(false);
  const opener=useRef<HTMLElement|null>(null);
  useEffect(()=>{fetch("/api/overview").then(async r=>{if(!r.ok)throw new Error("unavailable");return r.json() as Promise<LossOverview>}).then(data=>{setOverview(data);setUnavailable(false)}).catch(()=>setUnavailable(true)).finally(()=>setLoading(false));},[]);
  useEffect(()=>{
    const handle=(event:Event)=>{event.preventDefault();opener.current=document.activeElement instanceof HTMLElement?document.activeElement:null;setOpen(true)};
    window.addEventListener("purchase-record:open",handle);
    if(new URLSearchParams(window.location.search).get("record")==="1"){
      const timer=window.setTimeout(()=>{setOpen(true);history.replaceState(null,"",window.location.pathname+window.location.hash)},0);
      return()=>{window.clearTimeout(timer);window.removeEventListener("purchase-record:open",handle)};
    }
    return()=>window.removeEventListener("purchase-record:open",handle);
  },[]);
  function changeOpen(next:boolean){setOpen(next);if(!next)requestAnimationFrame(()=>opener.current?.focus())}
  return <SiteShell><main>
    <section className="noise relative overflow-hidden border-b border-foreground/20">
      <div className="relative mx-auto max-w-[1380px] px-5 pb-10 pt-10 md:px-9 md:pb-14 md:pt-14">
        <div className="flex items-start justify-between gap-4 gallery-label text-muted-foreground"><span>Buyer report index <span className="mx-2">/</span> PHP</span><span className="hidden sm:block">No. 001 — Ongoing</span></div>
        <div className="mt-10 grid gap-7 lg:grid-cols-[1fr_280px] lg:items-end">
          <div><h1 className="max-w-[1030px] text-[clamp(2.8rem,10.6vw,10rem)] font-semibold leading-[.77] tracking-[-.095em]">UNRESOLVED<span className="block text-[.72em] tracking-[-.085em]">LOSSES<span className="font-normal">.</span></span></h1></div>
          <div className="max-w-sm lg:pb-1"><p className="gallery-label mb-3 text-muted-foreground">Find a seller</p><SellerSearch hero/><a href="#gallery" className="mt-5 inline-flex min-h-11 items-center gap-3 text-xs font-medium uppercase tracking-[.12em] hover:underline">View the index <ArrowDown size={14}/></a></div>
        </div>
      </div>
    </section>

    <section id="gallery" className="mx-auto max-w-[1380px] px-5 pb-16 pt-7 md:px-9 md:pt-10">
      <div className="mb-4 flex items-end justify-between gap-4 border-b border-foreground/20 pb-3 gallery-label"><span>Featured profiles <span className="ml-2 text-muted-foreground">/ 01—03</span></span><span className="text-muted-foreground">Ranked by unresolved amount</span></div>
      <div className="grid gap-3 lg:grid-cols-[1.45fr_1fr]">
        <ProfileCard rank={1} seller={overview.leaders[0]} featured loading={loading}/>
        <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-1"><ProfileCard rank={2} seller={overview.leaders[1]} loading={loading}/><ProfileCard rank={3} seller={overview.leaders[2]} loading={loading}/></div>
      </div>
      <div className="mt-5 flex flex-wrap items-center justify-between gap-4 text-xs text-muted-foreground"><span role="status">{loading?"Loading index…":unavailable?"Live ranking unavailable until the data service is connected.":`${overview.totals.visible_sellers} sellers · ${overview.totals.report_count} reviewed reports`}</span><RecordTrigger label="Report unresolved loss" className="rounded-sm"/></div>
    </section>

    <section className="border-t border-foreground/20 bg-card"><div className="mx-auto max-w-[1380px] px-5 py-14 md:px-9 md:py-20">
      <div className="flex flex-wrap items-end justify-between gap-5"><div><p className="gallery-label text-muted-foreground">The full index</p><h2 className="mt-2 text-[clamp(2.55rem,8vw,7rem)] font-semibold leading-[.85] tracking-[-.085em]">LEADERBOARD.</h2></div><span className="gallery-label text-muted-foreground">Open reports / PHP</span></div>
      <div className="mt-10 border-t-2 border-foreground">
        {loading?<div className="py-14 text-sm text-muted-foreground" role="status">Loading reports…</div>:unavailable?<Unavailable/>:overview.leaders.length?overview.leaders.map((seller,index)=><Link key={seller.id} href={`/seller/${seller.normalized_username}`} className="group grid min-h-22 grid-cols-[42px_1fr_auto] items-center gap-3 border-b border-foreground/20 py-4 transition-colors hover:bg-foreground hover:px-4 hover:text-background md:grid-cols-[90px_1fr_180px_140px_24px] md:gap-5"><span className="gallery-label opacity-55">{String(index+1).padStart(2,"0")}</span><span className="min-w-0 truncate text-xl font-semibold tracking-[-.05em] md:text-3xl">@{seller.username}</span><span className="font-mono text-base font-medium tabular md:text-lg">{money(seller.unresolved_amount)}</span><span className="hidden gallery-label opacity-55 md:block">{seller.report_count} {seller.report_count===1?"report":"reports"}</span><ArrowUpRight className="hidden size-4 md:block"/></Link>):<div className="grid min-h-64 place-items-center border-b border-foreground/20 text-center"><div><p className="text-4xl font-semibold tracking-[-.06em]">No reviewed reports yet.</p><p className="mt-3 text-sm text-muted-foreground">Profiles appear after moderator approval.</p></div></div>}
      </div>
      <div className="mt-7 flex flex-wrap items-start justify-between gap-4 text-xs leading-5 text-muted-foreground"><p className="max-w-xl">Buyer reports are reviewed for inclusion, not independently verified. An unresolved amount is a reported claim, not a finding of fraud.</p><Link href="/methodology" className="inline-flex min-h-8 items-center gap-2 font-semibold text-foreground underline underline-offset-4">How rankings work <ArrowRight size={13}/></Link></div>
    </div></section>
    <LossDialog open={open} onOpenChange={changeOpen} siteKey={siteKey} ready={ready}/>
  </main></SiteShell>;
}

function ProfileCard({seller,rank,featured=false,loading=false}:{seller?:SellerLossStats;rank:number;featured?:boolean;loading?:boolean}){
  const content=<motion.div initial={{opacity:.6,y:8}} animate={{opacity:1,y:0}} transition={{duration:.35,delay:rank*.06}} className={`gallery-card group flex h-full min-h-[270px] flex-col justify-between border p-5 transition-colors md:p-7 ${featured?"min-h-[580px] border-foreground bg-foreground text-background lg:min-h-[620px]":"border-foreground/25 bg-background text-foreground lg:min-h-[303px]"}`}>
    <div className="relative flex justify-between gallery-label"><span>PROFILE / {String(rank).padStart(2,"0")}</span><span>{seller?"OPEN REPORTS":"UNASSIGNED"}</span></div>
    <div className="relative min-w-0"><span className={`pointer-events-none absolute bottom-[55%] -left-4 select-none font-semibold leading-none tracking-[-.12em] opacity-[.08] ${featured?"text-[clamp(12rem,29vw,31rem)]":"text-[13rem]"}`} aria-hidden="true">{rank}</span>{seller?<><p className={`truncate font-semibold leading-[.9] tracking-[-.075em] ${featured?"text-[clamp(3.7rem,7vw,7.6rem)]":"text-[clamp(2.8rem,4vw,4.7rem)]"}`}>@{seller.username}</p><div className="mt-8 flex items-end justify-between gap-4 border-t border-current/30 pt-4"><div><p className="gallery-label opacity-60">Unresolved amount</p><p className={`mt-2 font-mono font-medium tabular tracking-[-.055em] ${featured?"text-[clamp(2.6rem,5vw,5.4rem)]":"text-[clamp(1.8rem,3vw,2.7rem)]"}`}>{money(seller.unresolved_amount)}</p><p className="mt-3 gallery-label opacity-60">{seller.report_count} approved {seller.report_count===1?"report":"reports"}</p></div><ArrowUpRight className="size-6 shrink-0 transition-transform group-hover:-translate-y-1 group-hover:translate-x-1"/></div></>:<div className="border-t border-current/30 pt-5"><p className={`font-semibold tracking-[-.06em] ${featured?"text-5xl md:text-7xl":"text-3xl"}`}>{loading?"Loading…":"No profile yet"}</p><p className="mt-3 gallery-label opacity-55">Awaiting reviewed reports</p></div>}</div>
  </motion.div>;
  return seller?<Link href={`/seller/${seller.normalized_username}`} aria-label={`View @${seller.username}, ranked ${rank}, ${money(seller.unresolved_amount)} reported unresolved`} className="block h-full focus-visible:outline-offset-4">{content}</Link>:<div className="h-full">{content}</div>;
}

function Unavailable(){return <div role="status" className="grid min-h-56 place-items-center border border-foreground/25 p-8 text-center"><div><p className="text-2xl font-semibold">The index is unavailable.</p><p className="mt-2 text-sm text-muted-foreground">Try again after the data service is connected.</p></div></div>}

function LossDialog({open,onOpenChange,siteKey,ready}:{open:boolean;onOpenChange:(open:boolean)=>void;siteKey:string;ready:boolean}){
  const [handle,setHandle]=useState(""),[buyerUsername,setBuyerUsername]=useState(""),[suggestions,setSuggestions]=useState<SellerLossStats[]>([]),[quantity,setQuantity]=useState("1"),[price,setPrice]=useState(""),[date,setDate]=useState(manilaToday),[unresolved,setUnresolved]=useState(""),[issue,setIssue]=useState(""),[details,setDetails]=useState(""),[error,setError]=useState(""),[success,setSuccess]=useState(false),[saving,setSaving]=useState(false);
  const idempotency=useRef(""),formRef=useRef<HTMLFormElement>(null);
  useEffect(()=>{if(!idempotency.current)idempotency.current=crypto.randomUUID()},[]);
  useEffect(()=>{const normalized=normalizeHandle(handle);const timer=setTimeout(()=>{if(!normalized){setSuggestions([]);return}fetch(`/api/sellers?search=${encodeURIComponent(normalized)}`).then(async r=>r.ok?r.json() as Promise<SellerLossStats[]>:[]).then(setSuggestions).catch(()=>setSuggestions([]))},220);return()=>clearTimeout(timer)},[handle]);
  const total=useMemo(()=>{const value=Number(quantity)*Number(price);return Number.isFinite(value)&&value>0?money(value):"₱0"},[quantity,price]);
  const validAmount=validUnresolvedAmount(unresolved,quantity,price);
  function reset(){setHandle("");setBuyerUsername("");setSuggestions([]);setQuantity("1");setPrice("");setDate(manilaToday());setUnresolved("");setIssue("");setDetails("");setError("");setSuccess(false);idempotency.current=crypto.randomUUID();if(formRef.current){const file=formRef.current.querySelector<HTMLInputElement>("#loss-evidence");if(file)file.value=""}}
  async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setError("");if(!validForumUsername(buyerUsername)){setError("Enter your forum username (2 to 64 characters).");return}if(!validHandle(handle)){setError("Enter a valid seller handle.");return}if(!validAmount){setError("Enter an unresolved amount up to the purchase total.");return}if(!issue){setError("Choose what remains unresolved.");return}if(details.trim().length<10){setError("Add at least 10 characters describing what happened.");return}if(!ready){setError("Reporting is unavailable until the data service is configured.");return}const form=new FormData(event.currentTarget);form.set("buyerUsername",buyerUsername.trim());form.set("seller",normalizeHandle(handle));form.set("purchaseDate",date);form.set("quantity",quantity);form.set("unitPrice",price);form.set("unresolvedAmount",unresolved);form.set("issueType",issue);form.set("details",details.trim());form.set("idempotencyKey",idempotency.current);form.set("turnstileToken",String(form.get("cf-turnstile-response")||""));setSaving(true);try{const response=await fetch("/api/loss-reports",{method:"POST",body:form});const result=await response.json() as {error?:string};if(!response.ok)throw new Error(result.error||"We couldn't save the report.");setSuccess(true)}catch(e){setError(e instanceof Error?e.message:"We couldn't save the report.")}finally{setSaving(false)}}
  const input="h-12 w-full rounded-sm border border-foreground/25 bg-card px-3 text-sm outline-none focus:border-foreground";
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[calc(100dvh-1rem)] w-[calc(100%-1rem)] max-w-[960px] overflow-y-auto rounded-sm border border-foreground bg-card p-0 shadow-[var(--shadow-float)] sm:max-w-[960px] md:max-h-[calc(100dvh-3rem)]">
    {success?<div className="grid min-h-[520px] place-items-center p-8 text-center"><div><span className="mx-auto grid size-14 place-items-center rounded-full bg-foreground text-background"><Check size={24}/></span><p className="mt-7 gallery-label text-muted-foreground">Submission received</p><DialogTitle className="mt-3 text-5xl font-semibold tracking-[-.07em]">Pending review.</DialogTitle><DialogDescription className="mx-auto mt-4 max-w-sm text-sm leading-6">The report enters the public index only if a moderator approves it.</DialogDescription><div className="mt-8 flex flex-wrap justify-center gap-2"><button onClick={()=>onOpenChange(false)} className="min-h-11 border border-foreground px-5 text-sm font-semibold">Close</button><button onClick={reset} className="min-h-11 bg-foreground px-5 text-sm font-semibold text-background">Report another loss</button></div></div></div>:<div className="grid md:grid-cols-[1.15fr_.85fr]"><div className="p-6 md:p-9"><p className="gallery-label text-muted-foreground">Private submission / 01</p><DialogTitle className="mt-4 text-4xl font-semibold leading-[.95] tracking-[-.065em] md:text-5xl">Report an unresolved loss.</DialogTitle><DialogDescription className="mt-3 max-w-md text-sm leading-6">Reports are reviewed before they appear in the index.</DialogDescription>
      <form ref={formRef} onSubmit={submit} className="mt-8 space-y-5" noValidate><div className="grid gap-3 sm:grid-cols-2"><div><label htmlFor="loss-buyer" className="mb-2 block text-xs font-semibold">Your forum username</label><input id="loss-buyer" value={buyerUsername} onChange={e=>setBuyerUsername(e.target.value)} autoComplete="off" maxLength={64} placeholder="Your username" aria-describedby="buyer-privacy" className={input}/><p id="buyer-privacy" className="mt-1 text-[11px] text-muted-foreground">Only moderators can see this.</p></div><div><label htmlFor="loss-seller" className="mb-2 block text-xs font-semibold">Seller’s forum username</label><input id="loss-seller" list="seller-suggestions" value={handle} onChange={e=>setHandle(e.target.value)} autoComplete="off" placeholder="@seller" className={input}/><datalist id="seller-suggestions">{suggestions.map(s=><option value={s.normalized_username} key={s.id}/>)}</datalist></div></div>
        <div className="grid grid-cols-2 gap-3"><div><label htmlFor="loss-date" className="mb-2 block text-xs font-semibold">Purchase date</label><input id="loss-date" type="date" value={date} max={manilaToday()} min="2000-01-01" onChange={e=>setDate(e.target.value)} className={input}/></div><div><label htmlFor="loss-quantity" className="mb-2 block text-xs font-semibold">Accounts bought</label><input id="loss-quantity" type="number" min="1" max="10000" step="1" value={quantity} onChange={e=>setQuantity(e.target.value)} className={input}/></div></div>
        <div className="grid grid-cols-2 gap-3"><div><label htmlFor="loss-price" className="mb-2 block text-xs font-semibold">Price per account · PHP</label><input id="loss-price" type="number" min="0.01" max="1000000" step="0.01" inputMode="decimal" value={price} onChange={e=>setPrice(e.target.value)} className={input}/></div><div><label htmlFor="loss-unresolved" className="mb-2 block text-xs font-semibold">Still unresolved · PHP</label><input id="loss-unresolved" type="number" min="0.01" step="0.01" inputMode="decimal" value={unresolved} onChange={e=>setUnresolved(e.target.value)} aria-describedby="amount-hint" className={input}/></div></div><p id="amount-hint" className="text-xs text-muted-foreground">Up to the purchase total: {total}</p>
        <div><label htmlFor="loss-issue" className="mb-2 block text-xs font-semibold">What remains unresolved?</label><select id="loss-issue" value={issue} onChange={e=>setIssue(e.target.value)} className={input}><option value="">Select an issue</option><option value="not_delivered">Not delivered</option><option value="refund_not_received">Refund not received</option><option value="other_unresolved">Other unresolved issue</option></select></div>
        <div><label htmlFor="loss-details" className="mb-2 block text-xs font-semibold">Brief description · private</label><textarea id="loss-details" value={details} onChange={e=>setDetails(e.target.value)} minLength={10} maxLength={500} rows={3} placeholder="What happened, and what remains unresolved?" className={`${input} h-auto min-h-24 py-3`}/></div>
        <div><label htmlFor="loss-evidence" className="mb-2 block text-xs font-semibold">Image evidence · optional and private</label><input id="loss-evidence" name="evidence" type="file" accept="image/jpeg,image/png,image/webp" className="block w-full text-xs file:mr-3 file:min-h-10 file:border file:border-foreground/25 file:bg-background file:px-3 file:text-xs file:font-semibold"/><p className="mt-2 text-xs text-muted-foreground">JPG, PNG, or WebP · up to 5 MB</p></div>
        {siteKey&&<><Script src="https://challenges.cloudflare.com/turnstile/v0/api.js" strategy="afterInteractive"/><div className="cf-turnstile" data-sitekey={siteKey}/></>}
        {!ready&&<p role="status" className="border border-foreground/25 p-3 text-xs leading-5">Submissions open after the data service, private storage, bot protection, and administrator access are configured.</p>}{error&&<p role="alert" className="border border-foreground bg-background p-3 text-xs">{error}</p>}
        <div className="flex flex-wrap gap-2 pt-2"><button type="submit" disabled={!ready||saving} className="min-h-12 bg-foreground px-5 text-sm font-semibold text-background disabled:cursor-not-allowed disabled:opacity-40">{saving?"Submitting…":"Submit for review"}</button><button type="button" onClick={()=>{reset();onOpenChange(false)}} className="inline-flex min-h-12 items-center gap-2 border border-foreground/25 px-4 text-xs font-semibold"><X size={14}/>Discard</button></div>
      </form></div><aside className="gallery-card noise relative hidden min-h-full flex-col justify-between bg-foreground p-9 text-background md:flex"><div className="gallery-label relative">fraus / PHP</div><div className="relative"><p className="font-semibold leading-[.9] tracking-[-.08em] text-[5rem]">@</p><p className="mt-8 gallery-label opacity-55">Calculated purchase total</p><p className="mt-2 break-all font-mono text-4xl font-medium tabular">{total}</p><div className="mt-6 border-t border-background/25 pt-6"><p className="gallery-label opacity-55">Amount still unresolved</p><p className="mt-2 break-all font-mono text-3xl font-medium tabular">{validAmount?money(unresolved):"—"}</p></div></div></aside></div>}
  </DialogContent></Dialog>;
}
