"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import Script from "next/script";
import { SiteShell } from "@/components/site-shell";
import { RecentRecords, SellerPanel } from "@/components/public-ui";
import { Combobox, ComboboxInput, ComboboxContent, ComboboxList, ComboboxItem, ComboboxEmpty } from "@/components/ui/combobox";
import { manilaToday, money, normalizeHandle, validHandle, type PublicPurchase, type SellerStats } from "@/lib/domain";

export function HomeClient({siteKey,ready}:{siteKey:string;ready:boolean}) {
  const [handle,setHandle]=useState(""); const [selected,setSelected]=useState<string|null>(null);
  const [suggestions,setSuggestions]=useState<SellerStats[]>([]); const [seller,setSeller]=useState<SellerStats|null>(null); const [history,setHistory]=useState<PublicPurchase[]>([]);
  const [recent,setRecent]=useState<PublicPurchase[]>([]); const [quantity,setQuantity]=useState("1"); const [price,setPrice]=useState(""); const [date,setDate]=useState(manilaToday);
  const [status,setStatus]=useState(""); const [error,setError]=useState(""); const [loading,setLoading]=useState(false); const [saving,setSaving]=useState(false); const [recordsUnavailable,setRecordsUnavailable]=useState(false);
  const idempotency=useRef(""); const formRef=useRef<HTMLFormElement>(null);
  useEffect(()=>{idempotency.current=crypto.randomUUID();fetch("/api/records").then(async r=>{if(!r.ok)throw new Error("unavailable");return await r.json() as PublicPurchase[];}).then(setRecent).catch(()=>setRecordsUnavailable(true));},[]);
  useEffect(()=>{const h=normalizeHandle(handle); if(!h){setSuggestions([]);return;} const t=setTimeout(()=>{fetch(`/api/sellers?search=${encodeURIComponent(h)}`).then(async r=>r.ok?await r.json() as SellerStats[]:[]).then(setSuggestions).catch(()=>setSuggestions([]));},220); return ()=>clearTimeout(t);},[handle]);
  useEffect(()=>{if(!selected){setSeller(null);setHistory([]);return;} let live=true; setLoading(true);fetch(`/api/sellers/${encodeURIComponent(selected)}`).then(async r=>r.ok?await r.json() as {seller:SellerStats;purchases:PublicPurchase[]}:null).then(data=>{if(live){setSeller(data?.seller||null);setHistory(data?.purchases||[]);}}).catch(()=>{if(live){setSeller(null);setHistory([]);}}).finally(()=>{if(live)setLoading(false);});return()=>{live=false};},[selected]);
  const total=useMemo(()=>{const q=Number(quantity),p=Number(price);return Number.isFinite(q*p)&&q>0&&p>0?money(q*p):"₱0";},[quantity,price]);
  const match=suggestions.some(s=>s.normalized_username===normalizeHandle(handle));
  async function submit(event:React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); setError("");setStatus("");
    if(!validHandle(handle)){setError("Enter a valid seller handle.");return;}
    if(!ready){setError("Submissions are temporarily unavailable.");return;}
    const form=new FormData(event.currentTarget);
    form.set("seller",normalizeHandle(handle));form.set("purchaseDate",date);form.set("quantity",quantity);form.set("unitPrice",price);form.set("idempotencyKey",idempotency.current);
    form.set("turnstileToken",String(form.get("cf-turnstile-response")||""));
    setSaving(true);
    try {const response=await fetch("/api/purchases",{method:"POST",body:form});const result=await response.json() as {error?:string};if(!response.ok)throw new Error(result.error||"We couldn't save this purchase.");setStatus("Purchase recorded. Pending review. Public totals will update after approval.");setQuantity("1");setPrice("");if(formRef.current){const file=formRef.current.querySelector<HTMLInputElement>("#evidence");if(file)file.value="";}idempotency.current=crypto.randomUUID();}
    catch(e){setError(e instanceof Error?e.message:"We couldn't save this purchase.");}
    finally{setSaving(false);}
  }
  return <SiteShell><main className="mx-auto max-w-[1160px] px-5 pb-20 pt-10 md:px-8 md:pt-14"><div className="grid gap-6 lg:grid-cols-[1.04fr_.96fr]">
    <section className="rounded-xl border border-border bg-white p-6 md:p-8"><div className="mb-8"><p className="mb-2 text-xs font-semibold uppercase tracking-[.14em] text-primary">Buyer record</p><h1 className="text-[30px] font-semibold tracking-[-.055em] md:text-[34px]">Record a purchase</h1><p className="mt-2 text-[15px] text-muted-foreground">Add a purchase to the buyer-reported sales record.</p></div>
    <form ref={formRef} onSubmit={submit} className="space-y-5" noValidate><div><label className="mb-2 block text-sm font-medium" htmlFor="seller">Seller</label><Combobox items={[...suggestions.map(s=>s.normalized_username),...(!match&&validHandle(handle)?[normalizeHandle(handle)]:[])]} value={selected} onValueChange={value=>{const next=value||"";setSelected(next||null);setHandle(next);}} onInputValueChange={value=>{setHandle(value);if(normalizeHandle(value)!==selected)setSelected(null);}}><ComboboxInput id="seller" showTrigger={false} placeholder="Search or enter a seller handle" className="w-full [&_[data-slot=input-group-input]]:h-12"/><ComboboxContent><ComboboxList>{suggestions.map(s=><ComboboxItem key={s.id} value={s.normalized_username}>@{s.username}</ComboboxItem>)}{!match&&validHandle(handle)&&<ComboboxItem value={normalizeHandle(handle)}>Add @{normalizeHandle(handle)}</ComboboxItem>}<ComboboxEmpty>No matching seller.</ComboboxEmpty></ComboboxList></ComboboxContent></Combobox><p className="mt-2 text-xs text-muted-foreground">Use the seller&apos;s public handle. New sellers can be added here.</p></div>
    <div><label className="mb-2 block text-sm font-medium" htmlFor="date">Purchase date</label><input id="date" type="date" value={date} max={manilaToday()} onChange={e=>setDate(e.target.value)} className="h-12 w-full rounded-md border border-input bg-white px-3.5 text-sm" required/></div>
    <div className="grid grid-cols-2 gap-4"><div><label className="mb-2 block text-sm font-medium" htmlFor="quantity">Accounts purchased</label><input id="quantity" type="number" min="1" max="10000" step="1" value={quantity} onChange={e=>setQuantity(e.target.value)} className="h-12 w-full rounded-md border border-input bg-white px-3.5 text-sm" required/></div><div><label className="mb-2 block text-sm font-medium" htmlFor="price">Price per account</label><div className="flex h-12 items-center rounded-md border border-input bg-white"><span className="pl-3.5 text-sm text-muted-foreground">₱</span><input id="price" inputMode="decimal" pattern="[0-9]*[.]?[0-9]{0,2}" value={price} onChange={e=>setPrice(e.target.value)} placeholder="0.00" className="min-w-0 flex-1 px-2 text-sm outline-none" required/></div></div></div>
    <div className="rounded-lg border border-border bg-background px-4 py-4"><div className="flex justify-between text-sm text-muted-foreground"><span>Total paid</span><span>{quantity||"0"} × {price?money(price):"₱0"}</span></div><div className="mt-1 text-[27px] font-semibold tracking-[-.04em] tabular" aria-live="polite">{total}</div></div>
    <div><label className="mb-2 block text-sm font-medium" htmlFor="evidence">Supporting evidence <span className="font-normal text-muted-foreground">(optional)</span></label><input id="evidence" name="evidence" type="file" accept="image/jpeg,image/png,image/webp" className="block w-full rounded-md border border-dashed border-input bg-white p-3 text-sm file:mr-3 file:rounded file:border-0 file:bg-secondary file:px-3 file:py-1 file:text-foreground"/><p className="mt-2 text-xs text-muted-foreground">JPG, PNG or WebP, up to 5 MB. Please hide personal details. Evidence is private.</p></div>
    {siteKey&&<><Script src="https://challenges.cloudflare.com/turnstile/v0/api.js" strategy="afterInteractive"/><div className="cf-turnstile" data-sitekey={siteKey} data-theme="light"/></>}
    {!ready&&<p role="status" className="rounded-md border border-border bg-background px-3 py-3 text-sm text-muted-foreground">Purchase recording is temporarily unavailable while the service is being configured.</p>}{status&&<p role="status" className="rounded-md border border-[#c5ddd0] bg-[#f0f8f3] px-3 py-3 text-sm text-primary">{status}</p>}{error&&<p role="alert" className="rounded-md border border-[#efd3d3] bg-[#fff6f6] px-3 py-3 text-sm text-destructive">{error}</p>}
    <button disabled={saving||!ready} className="h-12 w-full rounded-md bg-primary text-sm font-semibold text-white hover:bg-[#113d35] disabled:cursor-not-allowed disabled:opacity-60">{saving?"Recording…":"Add purchase"}</button><p className="text-center text-xs text-muted-foreground">New purchases are reviewed before appearing publicly.</p></form></section>
    <SellerPanel seller={seller} rows={history} loading={loading}/></div>{recordsUnavailable?<section className="mt-12 rounded-xl border border-border bg-white p-6 text-sm text-muted-foreground">Public records are temporarily unavailable.</section>:<RecentRecords rows={recent}/>}</main></SiteShell>;
}
