"use client";
import Link from "next/link";
import { ChartNoAxesCombined, ArrowUpRight } from "lucide-react";
import { money, type SellerStats, type PublicPurchase } from "@/lib/domain";
import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from "@/components/ui/table";

const dateLabel = (date:string) => new Intl.DateTimeFormat("en-PH",{month:"short",day:"numeric",year:"numeric",timeZone:"UTC"}).format(new Date(`${date}T00:00:00Z`));
export function PriceHistory({rows}:{rows:PublicPurchase[]}) {
  const points = [...rows].sort((a,b)=>a.purchase_date.localeCompare(b.purchase_date) || a.created_at.localeCompare(b.created_at)).slice(-24);
  if (!points.length) return <p className="py-8 text-sm text-muted-foreground">No purchases have been recorded for this seller yet.</p>;
  const values = points.map(p=>Number(p.unit_price)); const min=Math.min(...values); const max=Math.max(...values); const span=Math.max(max-min,1);
  const coords=points.map((p,i)=>`${points.length===1?50:5+i*90/(points.length-1)},${72-(Number(p.unit_price)-min)/span*55}`).join(" ");
  return <div><div className="h-32 rounded-md bg-background px-2 py-3"><svg viewBox="0 0 100 85" preserveAspectRatio="none" role="img" aria-label={`Reported unit prices from ${money(min)} to ${money(max)}`} className="h-full w-full"><path d="M5 72 H95" stroke="#dce3de" strokeWidth=".6"/><polyline fill="none" stroke="#174f45" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round" points={coords}/>{points.map((p,i)=><circle key={p.id} cx={points.length===1?50:5+i*90/(points.length-1)} cy={72-(Number(p.unit_price)-min)/span*55} r="1.5" fill="#174f45"/>)}</svg></div><div className="mt-2 flex justify-between text-xs text-muted-foreground"><span>{dateLabel(points[0].purchase_date)}</span><span>{dateLabel(points[points.length-1].purchase_date)}</span></div></div>;
}
export function SellerPanel({seller,rows,loading=false,unavailable=false,draftHandle}:{seller:SellerStats|null;rows:PublicPurchase[];loading?:boolean;unavailable?:boolean;draftHandle?:string|null}) {
  return <section className="flex min-h-[360px] flex-col rounded-xl border border-border bg-white p-6 md:p-8 lg:min-h-[580px]"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.14em] text-muted-foreground">Seller overview</p><h2 className="mt-2 text-xl font-semibold tracking-[-.035em]">{seller?`@${seller.username}`:draftHandle?`@${draftHandle}`:"Reported activity"}</h2></div>{seller&&<Link href={`/seller/${seller.normalized_username}`} aria-label={`View @${seller.username} seller page`} className="rounded-md border border-border p-2 text-muted-foreground hover:text-primary"><ArrowUpRight size={16}/></Link>}</div>
  {seller?<div className="mt-9 flex-1"><p className="text-xs font-semibold uppercase tracking-[.14em] text-muted-foreground">Buyer-Reported Sales</p><p className="mt-2 text-[42px] font-semibold tracking-[-.07em] tabular md:text-[48px]">{money(seller.reported_sales)}</p><div className="mt-7 grid grid-cols-2 gap-x-5 gap-y-6 border-y border-border py-6"><Metric label="Accounts Reported Sold" value={String(seller.accounts_sold)}/><Metric label="Recorded Purchases" value={String(seller.recorded_purchases)}/><Metric label="Latest Reported Price" value={seller.latest_price?money(seller.latest_price):"—"}/><Metric label="Average Reported Price" value={seller.average_price?money(seller.average_price):"—"}/></div><h3 className="mb-3 mt-7 text-sm font-semibold">Price history</h3><PriceHistory rows={rows}/></div>:<div className="flex flex-1 flex-col items-center justify-center text-center"><div className="mb-5 grid size-14 place-items-center rounded-xl border border-border bg-background text-primary"><ChartNoAxesCombined size={22}/></div><h3 className="text-[17px] font-medium">{loading?"Loading seller…":unavailable?"Seller records unavailable":draftHandle?"No approved purchases":"No seller selected"}</h3><p className="mt-2 max-w-52 text-sm leading-6 text-muted-foreground">{loading?"Retrieving approved records.":unavailable?"Try again later.":draftHandle?"This seller has no public record yet.":"Select a seller to see their reported sales."}</p></div>}
  <div className="mt-8 border-t border-border pt-5 text-xs leading-5 text-muted-foreground">Buyer-Reported Sales are calculated from approved purchases submitted here. They do not represent complete revenue or profit.</div></section>;
}
function Metric({label,value}:{label:string;value:string}) {return <div><p className="text-xs leading-5 text-muted-foreground">{label}</p><p className="mt-1 text-xl font-semibold tracking-[-.035em] tabular">{value}</p></div>}
export function RecentRecords({rows,title="Recent records"}:{rows:PublicPurchase[];title?:string}) {
  return <section className="mt-12"><p className="text-xs font-semibold uppercase tracking-[.14em] text-primary">Public record</p><h2 className="mb-5 mt-1 text-[23px] font-semibold tracking-[-.04em]">{title}</h2>{!rows.length?<div className="rounded-xl border border-border bg-white px-6 py-16 text-center text-sm text-muted-foreground">No approved purchases have been recorded yet.</div>:<><div className="hidden rounded-xl border border-border bg-white px-4 md:block"><Table><TableHeader><TableRow><TableHead>Date</TableHead><TableHead>Seller</TableHead><TableHead>Quantity</TableHead><TableHead>Unit price</TableHead><TableHead>Total</TableHead><TableHead><span className="sr-only">Actions</span></TableHead></TableRow></TableHeader><TableBody>{rows.map(r=><TableRow key={r.id}><TableCell>{dateLabel(r.purchase_date)}</TableCell><TableCell><Link className="font-medium hover:text-primary" href={`/seller/${r.normalized_username}`}>@{r.username}</Link></TableCell><TableCell className="tabular">{r.quantity}</TableCell><TableCell className="tabular">{money(r.unit_price)}</TableCell><TableCell className="font-medium tabular">{money(r.total_amount)}</TableCell><TableCell><Link className="text-xs text-muted-foreground underline-offset-2 hover:underline" href={`/correct/${r.id}`}>Report issue</Link></TableCell></TableRow>)}</TableBody></Table></div><div className="space-y-3 md:hidden">{rows.map(r=><div key={r.id} className="rounded-xl border border-border bg-white p-4"><div className="flex justify-between"><Link href={`/seller/${r.normalized_username}`} className="font-medium">@{r.username}</Link><span className="font-semibold tabular">{money(r.total_amount)}</span></div><div className="mt-2 text-sm text-muted-foreground">{dateLabel(r.purchase_date)} · {r.quantity} × {money(r.unit_price)}</div><Link href={`/correct/${r.id}`} className="mt-3 inline-block text-xs text-muted-foreground underline">Report issue</Link></div>)}</div></>}</section>;
}
