import Link from "next/link";
import {SiteShell} from "@/components/site-shell";
import {RetroWindow,StatusStrip} from "@/components/retro-window";
import {ReactionImage,BlinkSticker} from "@/components/old-web-art";

const steps=[
  ["01","Reported","A buyer lists each software product, account quantity, and price per account. The site calculates the complete purchase value and initial unresolved amount. Their description and any image evidence stay private."],
  ["02","Reviewed","A moderator reviews the complete report before it can appear. Approval allows publication; it does not independently verify the purchase or establish wrongdoing."],
  ["03","Ranked","Each seller's current unresolved amounts are summed across approved open reports. Highest amount ranks first; tied amounts sort by normalized handle."],
  ["04","Measured","Reported purchase value sums the product subtotals, while accounts reported purchased sums their quantities. The mostly-sold product is the one with the highest reviewed open account quantity. These measures are not verified revenue or profit."],
  ["05","Corrected","Refunds and corrections can reduce or resolve an amount. Rejected, retracted, resolved, and older purchase-only records do not enter the public ranking."],
] as const;

export default function Methodology(){return <SiteShell><main className="archive-desk"><div className="grid gap-4 lg:grid-cols-[210px_minmax(0,1fr)]"><aside className="space-y-4"><RetroWindow title="FILE DIRECTORY" tone="lime" overflow="visible"><ReactionImage name="batman-thinking" className="method-batman"/><p className="gallery-label">Method / 001</p><p className="mt-3 text-xs leading-5">Five steps from private submission to a reviewed public record.</p><Link href="/#gallery" className="archive-button archive-button--paper mt-4 w-full">← Case files</Link></RetroWindow><BlinkSticker kind="warning"/></aside><RetroWindow title="HOW RANKINGS WORK / ARCHIVE MANUAL" tone="cobalt" bodyClassName="p-0" chrome="browser"><div className="border-b-2 border-foreground bg-[var(--warm-paper)] p-5 text-[var(--classic-ink)]"><span className="archive-stamp">Read before browsing</span><h1 className="archive-heading mt-3">How rankings work</h1></div><div className="grid gap-3 p-3 sm:grid-cols-2">{steps.map(([number,title,text],index)=><section key={number} className={`border-2 border-foreground bg-card p-4 ${index%2?"sm:translate-y-2":"sm:-rotate-[.25deg]"}`}><span className="archive-stamp">Step {number}</span><h2 className="display-type mt-3 text-lg">{title}</h2><p className="mt-2 text-sm leading-6">{text}</p></section>)}</div><StatusStrip><span>Reviewed buyer claims / not a finding of fraud</span></StatusStrip></RetroWindow></div><RetroWindow title="FINE PRINT / PRODUCT MARKS" tone="paper" className="method-fine-print mt-4" overflow="visible"><ReactionImage name="crocodile-suit" className="method-crocodile hidden sm:block"/><p className="max-w-3xl pr-0 text-sm leading-6 sm:pr-40">The index reflects only reports submitted to this site. Product marks identify reported products and do not imply affiliation or endorsement. The index is not complete revenue, profit, or a finding of fraud. Anyone can request a private correction from a public report.</p></RetroWindow></main></SiteShell>}
